### ISSUE TITLE
Switching to home assistant cloud caused some issues

### ISSUE THREAD

**Issue by jibbej** [mikewoudenberg/homeassistant-loqed#12] opened 2023-06-27 12:13 UTC
The integration worked like a charm until I switched to the home assistant cloud. After that the integration changed to no devices or entities with the message failed configuration. (instellen mislukt)
Any idea how to overcome this so that it works with the home assistant cloud?

**Comment by mikewoudenberg** [comment] 2023-06-27 12:22
The 0.9.0 version of this integration doesn't work with Home assistant Cloud (Nabu Casa). I'm experimenting with support for this on the main version of this branch. You could try to download the "Main" version of this integration (via HACS -> Integrations -> Loqed -> triple dot menu -> Redownload -> select version "Main") to try out whether that solves your issue.

**Comment by jibbej** [comment] 2023-06-27 13:36
> The 0.9.0 version of this integration doesn't work with Home assistant Cloud (Nabu Casa). I'm experimenting with support for this on the main version of this branch. You could try to download the "Main" version of this integration (via HACS -> Integrations -> Loqed -> triple dot menu -> Redownload -> select version "Main") to try out whether that solves your issue.
> 
> As soon as I confirm it to be working with both Nabu Casa, the duckdns addon and running Home Assistant behiond a standalone nginx proxy I'll release a new stable version

Downloaded the main branche but I still have the same outcome. I will keep an eye out for any changes in the future. Thanks for the support @mikewoudenberg

**Comment by mikewoudenberg** [comment] 2023-06-27 13:39
If you have any logging that you're willing to share, then maybe I can diagnose what the issue is.

**Comment by jibbej** [comment] 2023-06-27 13:41
> If you have any logging that you're willing to share, then maybe I can diagnose what the issue is.

Sure if I know where to find it. ;)

**Comment by mikewoudenberg** [comment] 2023-06-27 13:53
Go to Settings -> Integrations -> select the cogwheel (tandwiel) next to the Loqed integration. Selecte "Enable debug logging" (Should be under Known issues).

Now go to Settings -> System -> Logs to view the logs.

**Comment by jibbej** [comment] 2023-06-27 14:01
> Go to Settings -> Integrations -> select the cogwheel (tandwiel) next to the Loqed integration. Selecte "Enable debug logging" (Should be under Known issues).
> 
> Now go to Settings -> System -> Logs to view the logs.

Thanks.

Logger: homeassistant.config_entries
Source: helpers/network.py:206 
First occurred: 15:33:05 (1 occurrences) 
Last logged: 15:33:05

Error setting up entry LOQED Touch Smart Lock for loqed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/loqed/__init__.py", line 37, in async_setup_entry
    await coordinator.ensure_webhooks()
  File "/config/custom_components/loqed/coordinator.py", line 118, in ensure_webhooks
    webhook_url = webhook.async_generate_url(self.hass, webhook_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 92, in async_generate_url
    get_url(hass, prefer_external=True, allow_cloud=False),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 167, in get_url
    request_host = _get_request_host()
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 206, in _get_request_host
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

**Comment by mikewoudenberg** [comment] 2023-06-27 14:10
Thanks for the logs. For some reason this still is the v0.9.0 code. Are you sure you are running the "main" version of the integration (which has commit hash `ebc0df8`)?

**Comment by jibbej** [comment] 2023-06-27 14:18
> Thanks for the logs. For some reason this still is the v0.9.0 code. Are you sure you are running the "main" version of the integration (which has commit hash `ebc0df8`)?

I had a classic case of Gremlins I guess. Downloaded it twice and it kept saying v0.9.0 after reboot. Third time I had the right version and it seems to be working now.

**Comment by mikewoudenberg** [comment] 2023-06-27 14:24
Well you learn to debug along the way, so not an entire waste of effort :) Closing this because it's fixed then.

**Closed by mikewoudenberg** 2023-06-27 14:24 UTC
